# Generated by Django 5.0.4 on 2024-06-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.ad'),
        ),
    ]
