# Generated by Django 5.0.4 on 2024-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_description_ad_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='logo',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='advertiser_logos/'),
        ),
    ]
