# Generated by Django 5.0.4 on 2024-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ad_description_remove_ad_logo_advertiser_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='logo',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
