# Generated by Django 5.0.4 on 2024-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_advertiser_logo_advertiser_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
